/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 scene.gltf --transform 
Files: scene.gltf [48.04KB] > /home/will/Learning/crossy-road/src/assets/crossy_road_chicken_rigged/scene-transformed.glb [21.08KB] (56%)
Author: muffinhead3D (https://sketchfab.com/muffinhead3D)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/crossy-road-chicken-rigged-9bf2c7830fc0417daa9c8729818ccba4
Title: Crossy Road Chicken [Rigged]
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default (props) => {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('./models/chicken-transformed.glb')
  const { actions } = useAnimations(animations, group)

  return (
    <group ref={group} {...props} rotation={[0, Math.PI / -2, 0]} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="GLTF_SceneRootNode">
          <group name="Chicken_28" position={[0, 0.15, 0]}>
            <group name="GLTF_created_0">
              <primitive object={nodes.GLTF_created_0_rootJoint} />
              <skinnedMesh name="Object_7" geometry={nodes.Object_7.geometry} material={materials.blanc} skeleton={nodes.Object_7.skeleton} />
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('./models/chicken-transformed.glb')
